### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by miniupnp**
see http://travis-ci.org/
travis is a continuous integration solution.
The biggest issue is that logs are limited to 4MB. Usually ok, but not there :)

don't merge before it works :)

### CODE REVIEW

**Comment by miniupnp** [comment]
https://travis-ci.org/miniupnp/m68k-atari-mint-build

**Comment by miniupnp** [comment]
not good : The job exceeded the maximum time limit for jobs, and has been terminated.

**Comment by mikrosk** [comment]
This is very nice! I know about Travis, I've been thinking about something "one level up" -- having m68k-atari-mint-gcc + libs as dependencies and freemint/mintlib/etc as the targets. But this is also sweet.

Wouldn't solving #4 help the log size problem? I.e. we would have not one huge "make" but smaller packages/targets/whatever travis offers.

**Comment by miniupnp** [comment]
yep building for only one target should be OK

**Comment by mikrosk** [comment]
would it be possible to add the verbosity mute as an option? you know, many projects offer something as make V={0,1} where "0" means only some brief info like [CC] file or even [Compiling module XY].

Because right now if something goes wrong, you can't easily replicate the failing command (as you would see only the error message).

**Comment by mikrosk** [comment]
So what's the status of this one? Is there any chance I can talk you into changing the /dev/null statement into something more universal? Apart from that I have nothing against this PR, it's great.

**Comment by miniupnp** [comment]
I'm 1st trying to get it work, then I will fix the /dev/null stuff :)
I'm thinking : what do you think if output is redirected to a file ?

**Comment by miniupnp** [comment]
it is getting close ! https://travis-ci.org/miniupnp/m68k-atari-mint-build/builds/186360607

**Comment by miniupnp** [comment]
I think that's OK now thanks to commit https://github.com/mikrosk/m68k-atari-mint-build/pull/5/commits/a06cc45efa418b30b12bbcb2ccf319e27fe79bfc

we can overload travis-ci without loosing the log on our own machines ;)

**Comment by miniupnp** [comment]
OK I found the problem in mintlib Makefile :(
`@set fnord $(MAKEFLAGS)`
I think it should be `@set fnord "$(MAKEFLAGS)"`
I'm trying to circumvent the problem

**Comment by mikrosk** [comment]
Hmm, am I doing something wrong? If I type `make all`, everything is fine. But `make all OUT=/dev/null` gives me:
```
MAKE=make /usr/bin/bash build.sh --all
make[1]: Entering directory '/home/mikro/atari/compilers/m68k-atari-mint-build'
sed -e "s:\(MULTILIB_OPTIONS =\).*:\1 m68020-60/mcpu=5475 mshort:" -e "s:\(MULTILIB_DIRNAMES =\).*:\1 m68020-60 m5475 mshort:" gcc-4.6.4/gcc/config/m68k/t-mint > t-mint.patched
mv t-mint.patched gcc-4.6.4/gcc/config/m68k/t-mint
make[1]: Leaving directory '/home/mikro/atari/compilers/m68k-atari-mint-build'
make[1]: Entering directory '/home/mikro/atari/compilers/m68k-atari-mint-build'
mkdir -p binutils-2.26-m68000-cross
cd binutils-2.26-m68000-cross && \
PATH=/home/mikro/gnu-tools/m68000/bin:$PATH ../binutils-2.26/configure --target=m68k-atari-mint --prefix=/home/mikro/gnu-tools/m68000 --disable-nls --disable-werror && \
make /dev/null && \
make install-strip /dev/null
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... m68k-atari-mint
checking for a BSD-compatible install... /usr/bin/install -c
checking whether ln works... yes
checking whether ln -s works... yes
checking for a sed that does not truncate output... /usr/bin/sed
checking for gawk... gawk
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking whether g++ accepts -static-libstdc++ -static-libgcc... yes
checking for gnatbind... no
checking for gnatmake... no
checking whether compiler driver understands Ada... no
checking how to compare bootstrapped objects... cmp --ignore-initial=16 $$f1 $$f2
checking for objdir... .libs
checking for compatible ISL... yes
checking for default BUILD_CONFIG... 
checking for --enable-vtable-verify... no
checking for bison... bison -y
checking for bison... bison
checking for gm4... no
checking for gnum4... no
checking for m4... m4
checking for flex... flex
checking for flex... flex
checking for makeinfo... makeinfo
checking for expect... no
checking for runtest... no
checking for ar... ar
checking for as... as
checking for dlltool... no
checking for ld... ld
checking for lipo... no
checking for nm... nm
checking for ranlib... ranlib
checking for strip... strip
checking for windres... no
checking for windmc... no
checking for objcopy... objcopy
checking for objdump... objdump
checking for readelf... readelf
checking for m68k-atari-mint-cc... no
checking for m68k-atari-mint-gcc... m68k-atari-mint-gcc
checking for m68k-atari-mint-c++... m68k-atari-mint-c++
checking for m68k-atari-mint-gcc... m68k-atari-mint-gcc
checking for m68k-atari-mint-gcj... no
checking for m68k-atari-mint-gfortran... no
checking for m68k-atari-mint-gccgo... no
checking for m68k-atari-mint-ar... m68k-atari-mint-ar
checking for m68k-atari-mint-as... m68k-atari-mint-as
checking for m68k-atari-mint-dlltool... no
checking for m68k-atari-mint-ld... m68k-atari-mint-ld
checking for m68k-atari-mint-lipo... no
checking for m68k-atari-mint-nm... m68k-atari-mint-nm
checking for m68k-atari-mint-objcopy... m68k-atari-mint-objcopy
checking for m68k-atari-mint-objdump... m68k-atari-mint-objdump
checking for m68k-atari-mint-ranlib... m68k-atari-mint-ranlib
checking for m68k-atari-mint-readelf... m68k-atari-mint-readelf
checking for m68k-atari-mint-strip... m68k-atari-mint-strip
checking for m68k-atari-mint-windres... no
checking for m68k-atari-mint-windmc... no
checking where to find the target ar... just compiled
checking where to find the target as... just compiled
checking where to find the target cc... pre-installed
checking where to find the target c++... pre-installed
checking where to find the target c++ for libstdc++... pre-installed
checking where to find the target dlltool... just compiled
checking where to find the target gcc... pre-installed
checking where to find the target gcj... pre-installed
checking where to find the target gfortran... pre-installed
checking where to find the target gccgo... pre-installed
checking where to find the target ld... just compiled
checking where to find the target lipo... pre-installed
checking where to find the target nm... just compiled
checking where to find the target objcopy... just compiled
checking where to find the target objdump... just compiled
checking where to find the target ranlib... just compiled
checking where to find the target readelf... just compiled
checking where to find the target strip... just compiled
checking where to find the target windres... just compiled
checking where to find the target windmc... just compiled
checking whether to enable maintainer-specific portions of Makefiles... no
configure: creating ./config.status
config.status: creating Makefile
make[2]: Entering directory '/home/mikro/atari/compilers/m68k-atari-mint-build/binutils-2.26-m68000-cross'
make[2]: Nothing to be done for '/dev/null'.
make[2]: Leaving directory '/home/mikro/atari/compilers/m68k-atari-mint-build/binutils-2.26-m68000-cross'
make[2]: Entering directory '/home/mikro/atari/compilers/m68k-atari-mint-build/binutils-2.26-m68000-cross'
make[3]: Entering directory '/home/mikro/atari/compilers/m68k-atari-mint-build/binutils-2.26-m68000-cross'
/bin/sh ../binutils-2.26/mkinstalldirs /home/mikro/gnu-tools/m68000 /home/mikro/gnu-tools/m68000
/bin/sh: line 3: cd: ./bfd: No such file or directory
make[3]: *** [Makefile:2790: install-strip-bfd] Error 1
make[3]: Leaving directory '/home/mikro/atari/compilers/m68k-atari-mint-build/binutils-2.26-m68000-cross'
make[2]: *** [Makefile:2395: install-strip] Error 2
make[2]: Leaving directory '/home/mikro/atari/compilers/m68k-atari-mint-build/binutils-2.26-m68000-cross'
make[1]: *** [Makefile:150: binutils-2.26-m68000-cross] Error 2
make[1]: Leaving directory '/home/mikro/atari/compilers/m68k-atari-mint-build'
make: *** [Makefile:49: all] Error 1
```

**Comment by miniupnp** [comment]
`make all OUT="> /dev/null"` just as in the .travis.yml file

**Comment by mikrosk** [comment]
OK, I was a little bit tired. ;) Thanks again!

**Comment by miniupnp** [comment]
@mikrosk you should (could ?) go to http://travis-ci.org and activate it for repository https://github.com/mikrosk/m68k-atari-mint-build/

**Comment by mikrosk** [comment]
OK, I've done it (and activated it as well). It says the auto build would be enabled after another commit so... have you something in the pipeline? ;)

**Comment by miniupnp** [comment]
yes ;)

**Pull request merged**
