### PR TITLE
do not try to create ${INSTALL_DIR}/${TARGET}/usr symlink if it alrea…

### PR DESCRIPTION
**Pull request by miniupnp**
…dy exists

### CODE REVIEW

**Comment by TheFakeMontyOnTheRun** [comment]
Sorry to disturb an ancient PR, but I'm facing issues building this on OSX and I suspect this PR was supposed to fix it...but I'm facing the issues regardless.

Is this supposed to fix this?
```
ln -sfv . /Users/monty/gnu-tools/m68000/m68k-atari-mint/usr
ln: /Users/monty/gnu-tools/m68000/m68k-atari-mint/usr/.: Operation not permitted
make[1]: *** [gcc-7.2.0-m68000-cross-preliminary.ok] Error 1
make: *** [all-skip-native] Error 1

```

Where I should be looking to ameliorate the problem?
Thanks for all the effort!

**Comment by miniupnp** [comment]
@TheFakeMontyOnTheRun does the patch fix your issue ?

**Comment by TheFakeMontyOnTheRun** [comment]
Ooops, my bad - I was at the wrong branch.

But now, I have another error:

```
patching file configure
touch mintbin-CVS-20110527.ok
rm -rf mintlib.ok mintlib-master
/usr/bin/tar xzf master.tar.gz > /dev/null
cd mintlib-master && patch -p1 < ../mintlib.patch
patching file syscall/Makefile
Hunk #1 succeeded at 9 (offset -1 lines).
Hunk #2 FAILED at 51.
1 out of 2 hunks FAILED -- saving rejects to file syscall/Makefile.rej
make[1]: *** [mintlib.ok] Error 1
make: *** [all-skip-native] Error 1

```

**Comment by mikrosk** [comment]
Ah sorry, I must have totally overlooked this PR. Merged a slightly different version. I wonder where that `mintbin-CVS-20110527.ok` comes from, this still looks like an ancient branch to me?

**Pull request closed without merging**
