### PR TITLE
compile under OS X

### PR DESCRIPTION
**Pull request by miniupnp**

### CODE REVIEW

**Comment by miniupnp** [comment]
@mikrosk you should see that travis-ci is automatically checking the PR :)

**Comment by mikrosk** [comment]
Whoa, what happened in `mintbin.patch`? Why so many changes?

**Comment by miniupnp** [comment]
config.sub/config.guess where so old they weren't aware of the existence of OS X.
so that gave the error `checking host system type... configure: error: can not guess host type; you must specify one`
The simpler solution was to update to latest config.sub/config.guess

**Comment by miniupnp** [comment]
I guess you can merge.

**Pull request merged**
