### PR TITLE
depack & patch in the same target. touch .ok file only if finished

### LINKED ISSUE #17: Detect fully unpacked and patched sources
Right now it's easy to mess up things if one presses CTRL+C during `tar xzf` and/or before `patch`. It should be pretty easy to create an empty file which would pose as a flag. Something like:

```
tar xjf gcc-4.6.4.tar.bz2
touch gcc-4.6.4/.source_ok
cd gcc-4.6.4
cat ../gcc.patch | patch -p1
touch .source_patched

```
or even simpler:

```
tar xjf gcc-4.6.4.tar.bz2
cd gcc-4.6.4
cat ../gcc.patch | patch -p1
touch .source_ok
```

Then we would check in `Makefile` whether the file exists and if not, we'd just delete the whole dir and unpacked/patched it again.

### PR DESCRIPTION
**Pull request by miniupnp**
fixes #017

### CODE REVIEW

**Comment by mikrosk** [comment]
Ha, much easier than I thought, good work! However, one minor thing has to be changed: right now we have no longer a possibility to add another platform (think of m68k-linux-gnu-elf or so) because the gcc mint patch (and possibly others) would be applied in all cases -- that's why I separated "gcc.patch" (generic build patch) and the mint one.

**Comment by miniupnp** [comment]
maybe we should put gcc patched for mint in a gcc-4.6.4-mint directory then...

**Comment by mikrosk** [comment]
That's the question -- whether to follow path "make clean first, then build your target" or "change the target and we will create another directory for it, side by side". The former approach is used in EmuTOS, the latter in FreeMiNT for example (but only on binary level).

My aim is to have, in the end, ability to compile various different m68k-atari-mint-gcc flavours (different ABIs):
- Vincent's gcc (https://github.com/mikrosk/m68k-atari-mint-gcc/tree/gcc-4_6-mint) [current one]
- PeyloW's fastcall version (https://github.com/mikrosk/m68k-atari-mint-gcc/commits/gcc-4_6-mint-fastcall)
- Armin's ELF version (https://github.com/ardi69/m68k-atari-mint-elf)
- GGN's and Doug's ELF version (https://bitbucket.org/ggnkua/bigbrownbuild/src)

The idea is to `git checkout` each branch (I plan to merge the last two into my repo as well), offer the user the targets and build the version he wishes to try, so one can easily compare output.

**Comment by miniupnp** [comment]
from the make point of view we need to have separated directories per patched version.
so gcc-{VERSION}-mint / gcc-{VERSION}-mint-fastcall /  gcc-{VERSION}-mint-elf / etc.

**Comment by mikrosk** [comment]
In case you don't do `make clean` in between. If you say "guys, when making a build for new platform, do make clean first", it doesn't really matter.

On the other hand, my gut tells me that depacking the same gcc sources over and over sounds silly. So all righty then, what about making like really, really right ;) -- we create not gcc-4.6.4 and then gcc-4.6.4-cross etc but let's make it a full scale directory name, say:

${TARGET}-gcc-${GCC_VERSION}-xxx
where 'xxx' would be -source, -cross-preliminary, -cross-final, -atari and TARGET would be m68k-atari-mint, m68k-atari-mint-fastcall etc ?

`${TARGET}-gcc-${GCC_VERSION}-source` would be then:

m68k-atari-mint-gcc-patch: "download and depack an archive"
    ...
    mv (single patch) $@
    
m68k-atari-mint-elf-gcc-patch: "download and depack an archive"
    ...
    mv (single patch file) $@

${TARGET}-gcc-${GCC_VERSION}-source: gcc-${GCC_VERSION}.tar.bz2 ${TARGET}-gcc-patch
    tar xjf gcc-${GCC_VERSION}.tar.bz2 # lazy to look up how to specify the dir in `tar`
    cat ${TARGET}-gcc-patch | patch -p1

What do you say? (now I realised that this actually depacks gcc archive over and over :D)

**Comment by miniupnp** [comment]
Maybe the patches are not incompatible.... I have to see. But if that is the case, only one source directory is ok (for packages that allow building a different directory than source such as binutils and gcc)

**Comment by mikrosk** [comment]
You're right, right now there's no reason not to commit this one, thanks again.

**Comment by mikrosk** [comment]
Just for the sake of completeness, I'm looking into the universal target/platform approach, so feel free to look into another (more entertaining ;-)) things.

**Pull request merged**
